### ISSUE TITLE
Sharp lines for charts with step interpolation

### ISSUE THREAD

**Issue by rightfold** [joewalnes/smoothie#57]
Step charts look quite fuzzy. It would be nice if there were an option for sharp lines, similar to the option that is available for grid lines.

**Comment by WofWca** [comment]
Workaround: consider `lineWidth: 2`

Possible solutions:
* Add/subtract 0.5 from `x` & `y` here: https://github.com/joewalnes/smoothie/blob/c849bef1fee6348630299846c9436a485289afda/smoothie.js#L970-L971
just as with grid's `sharpLines` . Though some might say that it makes the data displayed incorrect.
* Add an option called something like `offsetPixels` that would offset the whole canvas instead of just the data line. It's kind of conflicting with grid's `sharpLines` option though.
